
void Set(SerializedProperty p, object value) {
 if(p==null)throw new Exception("Missing property");
 if(value is string s)p.stringValue=s;
 else if(value is bool b)p.boolValue=b;
 else if(value is UnityEngine.Object o)p.objectReferenceValue=o;
 else if(value==null)p.objectReferenceValue=null;
 else if(p.propertyType==SerializedPropertyType.Integer || p.propertyType==SerializedPropertyType.Enum)p.intValue=Convert.ToInt32(value);
 else p.floatValue=Convert.ToSingle(value);
}
void Edit(string path, Action<SerializedObject> apply) {
 var asset=AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(path);if(asset==null)throw new Exception(path);
 var so=new SerializedObject(asset);apply(so);so.ApplyModifiedPropertiesWithoutUndo();EditorUtility.SetDirty(asset);
}
UnityEngine.Object Asset(string path)=>AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(path);
Edit("Assets/Configs/Gladiators/Murmillo.asset",so=>{Set(so.FindProperty("_maxHealth"),600);
Set(so.FindProperty("_moveSpeed"),2.4f);
Set(so.FindProperty("_attackDamage"),22);
Set(so.FindProperty("_attackRange"),0.9f);
Set(so.FindProperty("_attackCooldown"),1.1f);
Set(so.FindProperty("_attackWindup"),0.35f);
Set(so.FindProperty("_armor"),2);
Set(so.FindProperty("_critChance"),0.05f);
Set(so.FindProperty("_critMultiplier"),1.6f);
Set(so.FindProperty("_radius"),0.4f);
Set(so.FindProperty("_engagementCapacity"),5);
Set(so.FindProperty("_goldReward"),4);});
Edit("Assets/Configs/Gladiators/Retiatius.asset",so=>{Set(so.FindProperty("_maxHealth"),475);
Set(so.FindProperty("_moveSpeed"),2.8f);
Set(so.FindProperty("_attackDamage"),20);
Set(so.FindProperty("_attackRange"),1.25f);
Set(so.FindProperty("_attackCooldown"),1);
Set(so.FindProperty("_attackWindup"),0.3f);
Set(so.FindProperty("_armor"),0);
Set(so.FindProperty("_critChance"),0.08f);
Set(so.FindProperty("_critMultiplier"),1.6f);
Set(so.FindProperty("_radius"),0.35f);
Set(so.FindProperty("_engagementCapacity"),4);
Set(so.FindProperty("_goldReward"),4);});
Edit("Assets/Configs/Gladiators/Secutor.asset",so=>{Set(so.FindProperty("_maxHealth"),650);
Set(so.FindProperty("_moveSpeed"),2.5f);
Set(so.FindProperty("_attackDamage"),21);
Set(so.FindProperty("_attackRange"),0.9f);
Set(so.FindProperty("_attackCooldown"),1.15f);
Set(so.FindProperty("_attackWindup"),0.35f);
Set(so.FindProperty("_armor"),3);
Set(so.FindProperty("_critChance"),0.04f);
Set(so.FindProperty("_critMultiplier"),1.6f);
Set(so.FindProperty("_radius"),0.4f);
Set(so.FindProperty("_engagementCapacity"),5);
Set(so.FindProperty("_goldReward"),5);});
Edit("Assets/Configs/Gladiators/Thraex.asset",so=>{Set(so.FindProperty("_maxHealth"),450);
Set(so.FindProperty("_moveSpeed"),3.2f);
Set(so.FindProperty("_attackDamage"),19);
Set(so.FindProperty("_attackRange"),0.85f);
Set(so.FindProperty("_attackCooldown"),0.85f);
Set(so.FindProperty("_attackWindup"),0.25f);
Set(so.FindProperty("_armor"),1);
Set(so.FindProperty("_critChance"),0.15f);
Set(so.FindProperty("_critMultiplier"),1.8f);
Set(so.FindProperty("_radius"),0.35f);
Set(so.FindProperty("_engagementCapacity"),4);
Set(so.FindProperty("_goldReward"),4);});
Edit("Assets/Configs/Gladiators/Hoplomach.asset",so=>{Set(so.FindProperty("_maxHealth"),675);
Set(so.FindProperty("_moveSpeed"),2);
Set(so.FindProperty("_attackDamage"),24);
Set(so.FindProperty("_attackRange"),1.2f);
Set(so.FindProperty("_attackCooldown"),1.35f);
Set(so.FindProperty("_attackWindup"),0.4f);
Set(so.FindProperty("_armor"),4);
Set(so.FindProperty("_critChance"),0.05f);
Set(so.FindProperty("_critMultiplier"),1.6f);
Set(so.FindProperty("_radius"),0.42f);
Set(so.FindProperty("_engagementCapacity"),5);
Set(so.FindProperty("_goldReward"),6);});
Edit("Assets/Configs/Gladiators/Wolf.asset",so=>{Set(so.FindProperty("_maxHealth"),375);
Set(so.FindProperty("_moveSpeed"),3);
Set(so.FindProperty("_attackDamage"),10);
Set(so.FindProperty("_attackRange"),0.85f);
Set(so.FindProperty("_attackCooldown"),1);
Set(so.FindProperty("_attackWindup"),0.3f);
Set(so.FindProperty("_armor"),0);
Set(so.FindProperty("_critChance"),0);
Set(so.FindProperty("_critMultiplier"),1.5f);
Set(so.FindProperty("_radius"),0.35f);
Set(so.FindProperty("_engagementCapacity"),4);
Set(so.FindProperty("_goldReward"),2);});
Edit("Assets/Configs/Gladiators/Lion.asset",so=>{Set(so.FindProperty("_maxHealth"),875);
Set(so.FindProperty("_moveSpeed"),2.6f);
Set(so.FindProperty("_attackDamage"),30);
Set(so.FindProperty("_attackRange"),1);
Set(so.FindProperty("_attackCooldown"),1.4f);
Set(so.FindProperty("_attackWindup"),0.45f);
Set(so.FindProperty("_armor"),1);
Set(so.FindProperty("_critChance"),0.05f);
Set(so.FindProperty("_critMultiplier"),1.6f);
Set(so.FindProperty("_radius"),0.45f);
Set(so.FindProperty("_engagementCapacity"),5);
Set(so.FindProperty("_goldReward"),6);});
Edit("Assets/Configs/Buildings/Gymnasium.asset",so=>{Set(so.FindProperty("_displayName"),"Гимназия");
Set(so.FindProperty("_description"),"Каждый уровень: +8% урона всем гладиаторам.");var levels=so.FindProperty("_levels");levels.arraySize=3;var l0=levels.GetArrayElementAtIndex(0);Set(l0.FindPropertyRelative("_cost"),180);var m0=l0.FindPropertyRelative("_modifiers");m0.arraySize=1;
Set(m0.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),3);
Set(m0.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),2);
Set(m0.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.08f);
var l1=levels.GetArrayElementAtIndex(1);Set(l1.FindPropertyRelative("_cost"),360);var m1=l1.FindPropertyRelative("_modifiers");m1.arraySize=1;
Set(m1.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),3);
Set(m1.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),2);
Set(m1.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.08f);
var l2=levels.GetArrayElementAtIndex(2);Set(l2.FindPropertyRelative("_cost"),720);var m2=l2.FindPropertyRelative("_modifiers");m2.arraySize=1;
Set(m2.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),3);
Set(m2.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),2);
Set(m2.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.08f);});
Edit("Assets/Configs/Buildings/Hospital.asset",so=>{Set(so.FindProperty("_displayName"),"Лазарет");
Set(so.FindProperty("_description"),"Каждый уровень: +10% максимального здоровья всем гладиаторам.");var levels=so.FindProperty("_levels");levels.arraySize=3;var l0=levels.GetArrayElementAtIndex(0);Set(l0.FindPropertyRelative("_cost"),160);var m0=l0.FindPropertyRelative("_modifiers");m0.arraySize=1;
Set(m0.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),1);
Set(m0.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),2);
Set(m0.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.1f);
var l1=levels.GetArrayElementAtIndex(1);Set(l1.FindPropertyRelative("_cost"),320);var m1=l1.FindPropertyRelative("_modifiers");m1.arraySize=1;
Set(m1.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),1);
Set(m1.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),2);
Set(m1.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.1f);
var l2=levels.GetArrayElementAtIndex(2);Set(l2.FindPropertyRelative("_cost"),640);var m2=l2.FindPropertyRelative("_modifiers");m2.arraySize=1;
Set(m2.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),1);
Set(m2.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),2);
Set(m2.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.1f);});
Edit("Assets/Configs/Buildings/Forge.asset",so=>{Set(so.FindProperty("_displayName"),"Кузница");
Set(so.FindProperty("_description"),"Каждый уровень: +0,5 брони и +2 процентных пункта шанса крита всем гладиаторам.");var levels=so.FindProperty("_levels");levels.arraySize=3;var l0=levels.GetArrayElementAtIndex(0);Set(l0.FindPropertyRelative("_cost"),220);var m0=l0.FindPropertyRelative("_modifiers");m0.arraySize=2;
Set(m0.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),8);
Set(m0.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),1);
Set(m0.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.5f);
Set(m0.GetArrayElementAtIndex(1).FindPropertyRelative("_statId"),9);
Set(m0.GetArrayElementAtIndex(1).FindPropertyRelative("_modType"),1);
Set(m0.GetArrayElementAtIndex(1).FindPropertyRelative("_value"),0.02f);
var l1=levels.GetArrayElementAtIndex(1);Set(l1.FindPropertyRelative("_cost"),440);var m1=l1.FindPropertyRelative("_modifiers");m1.arraySize=2;
Set(m1.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),8);
Set(m1.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),1);
Set(m1.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.5f);
Set(m1.GetArrayElementAtIndex(1).FindPropertyRelative("_statId"),9);
Set(m1.GetArrayElementAtIndex(1).FindPropertyRelative("_modType"),1);
Set(m1.GetArrayElementAtIndex(1).FindPropertyRelative("_value"),0.02f);
var l2=levels.GetArrayElementAtIndex(2);Set(l2.FindPropertyRelative("_cost"),880);var m2=l2.FindPropertyRelative("_modifiers");m2.arraySize=2;
Set(m2.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),8);
Set(m2.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),1);
Set(m2.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.5f);
Set(m2.GetArrayElementAtIndex(1).FindPropertyRelative("_statId"),9);
Set(m2.GetArrayElementAtIndex(1).FindPropertyRelative("_modType"),1);
Set(m2.GetArrayElementAtIndex(1).FindPropertyRelative("_value"),0.02f);});
Edit("Assets/Configs/Buildings/Nets.asset",so=>{Set(so.FindProperty("_displayName"),"Школа сетей");
Set(so.FindProperty("_description"),"Каждый уровень: ретиариям +0,1 дальности и −3% перезарядки атаки.");var levels=so.FindProperty("_levels");levels.arraySize=3;var l0=levels.GetArrayElementAtIndex(0);Set(l0.FindPropertyRelative("_cost"),140);var m0=l0.FindPropertyRelative("_modifiers");m0.arraySize=2;
Set(m0.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),4);
Set(m0.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),1);
Set(m0.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.1f);
Set(m0.GetArrayElementAtIndex(1).FindPropertyRelative("_statId"),5);
Set(m0.GetArrayElementAtIndex(1).FindPropertyRelative("_modType"),2);
Set(m0.GetArrayElementAtIndex(1).FindPropertyRelative("_value"),-0.03f);
var l1=levels.GetArrayElementAtIndex(1);Set(l1.FindPropertyRelative("_cost"),280);var m1=l1.FindPropertyRelative("_modifiers");m1.arraySize=2;
Set(m1.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),4);
Set(m1.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),1);
Set(m1.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.1f);
Set(m1.GetArrayElementAtIndex(1).FindPropertyRelative("_statId"),5);
Set(m1.GetArrayElementAtIndex(1).FindPropertyRelative("_modType"),2);
Set(m1.GetArrayElementAtIndex(1).FindPropertyRelative("_value"),-0.03f);
var l2=levels.GetArrayElementAtIndex(2);Set(l2.FindPropertyRelative("_cost"),560);var m2=l2.FindPropertyRelative("_modifiers");m2.arraySize=2;
Set(m2.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),4);
Set(m2.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),1);
Set(m2.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.1f);
Set(m2.GetArrayElementAtIndex(1).FindPropertyRelative("_statId"),5);
Set(m2.GetArrayElementAtIndex(1).FindPropertyRelative("_modType"),2);
Set(m2.GetArrayElementAtIndex(1).FindPropertyRelative("_value"),-0.03f);});
Edit("Assets/Configs/Equipment/Gladius.asset",so=>{Set(so.FindProperty("_displayName"),"Гладиус");
Set(so.FindProperty("_description"),"Мурмиллонам +10% урона.");
Set(so.FindProperty("_price"),180);var m=so.FindProperty("_modifiers");m.arraySize=1;
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),3);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),2);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.1f);});
Edit("Assets/Configs/Equipment/Scutum.asset",so=>{Set(so.FindProperty("_displayName"),"Скутум");
Set(so.FindProperty("_description"),"Мурмиллонам +1 брони и +5% здоровья.");
Set(so.FindProperty("_price"),200);var m=so.FindProperty("_modifiers");m.arraySize=2;
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),8);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),1);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),1);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_statId"),1);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_modType"),2);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_value"),0.05f);});
Edit("Assets/Configs/Equipment/LorikaHlamata.asset",so=>{Set(so.FindProperty("_displayName"),"Лорика");
Set(so.FindProperty("_description"),"Всем гладиаторам +1 брони; складывается с классовым снаряжением.");
Set(so.FindProperty("_price"),300);var m=so.FindProperty("_modifiers");m.arraySize=1;
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),8);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),1);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),1);});
Edit("Assets/Configs/Equipment/Posca.asset",so=>{Set(so.FindProperty("_displayName"),"Поска");
Set(so.FindProperty("_description"),"Всем гладиаторам +8% здоровья.");
Set(so.FindProperty("_price"),160);var m=so.FindProperty("_modifiers");m.arraySize=1;
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),1);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),2);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.08f);});
Edit("Assets/Configs/Equipment/Pilum.asset",so=>{Set(so.FindProperty("_displayName"),"Пилум");
Set(so.FindProperty("_description"),"Ретиариям +10% урона и +0,1 дальности.");
Set(so.FindProperty("_id"),"item.pilum");
Set(so.FindProperty("_price"),200);var m=so.FindProperty("_modifiers");m.arraySize=2;
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),3);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),2);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.1f);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_statId"),4);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_modType"),1);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_value"),0.1f);});
Edit("Assets/Configs/Formations/Column.asset",so=>{Set(so.FindProperty("_displayName"),"Колонна");
Set(so.FindProperty("_description"),"+15% скорости, −5% здоровья.");
Set(so.FindProperty("_marchSpeed"),2.2f);
Set(so.FindProperty("_breakRange"),1.5f);
Set(so.FindProperty("_rankSpacing"),0.9f);
Set(so.FindProperty("_fileSpacing"),0.9f);var m=so.FindProperty("_modifiers");m.arraySize=2;
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),2);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),2);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.15f);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_statId"),1);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_modType"),2);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_value"),-0.05f);});
Edit("Assets/Configs/Formations/Circle.asset",so=>{Set(so.FindProperty("_displayName"),"Круг");
Set(so.FindProperty("_description"),"+10% здоровья, −5% урона.");
Set(so.FindProperty("_marchSpeed"),1.8f);
Set(so.FindProperty("_breakRange"),1.5f);
Set(so.FindProperty("_rankSpacing"),0.9f);
Set(so.FindProperty("_fileSpacing"),0.9f);var m=so.FindProperty("_modifiers");m.arraySize=2;
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),1);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),2);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.1f);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_statId"),3);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_modType"),2);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_value"),-0.05f);});
Edit("Assets/Configs/Formations/Testudo.asset",so=>{Set(so.FindProperty("_displayName"),"Черепаха");
Set(so.FindProperty("_description"),"+1,5 брони; −15% скорости, +8% времени перезарядки.");
Set(so.FindProperty("_marchSpeed"),1.6f);
Set(so.FindProperty("_breakRange"),1.5f);
Set(so.FindProperty("_rankSpacing"),0.9f);
Set(so.FindProperty("_fileSpacing"),0.9f);var m=so.FindProperty("_modifiers");m.arraySize=3;
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),8);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),1);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),1.5f);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_statId"),2);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_modType"),2);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_value"),-0.15f);
Set(m.GetArrayElementAtIndex(2).FindPropertyRelative("_statId"),5);
Set(m.GetArrayElementAtIndex(2).FindPropertyRelative("_modType"),2);
Set(m.GetArrayElementAtIndex(2).FindPropertyRelative("_value"),0.08f);});
Edit("Assets/Configs/Formations/Swine.asset",so=>{Set(so.FindProperty("_displayName"),"Клин");
Set(so.FindProperty("_description"),"+12% урона, −8% здоровья.");
Set(so.FindProperty("_marchSpeed"),2.2f);
Set(so.FindProperty("_breakRange"),1.5f);
Set(so.FindProperty("_rankSpacing"),0.9f);
Set(so.FindProperty("_fileSpacing"),0.9f);var m=so.FindProperty("_modifiers");m.arraySize=2;
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),3);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),2);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.12f);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_statId"),1);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_modType"),2);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_value"),-0.08f);});
Edit("Assets/Configs/Formations/Falang.asset",so=>{Set(so.FindProperty("_displayName"),"Фаланга");
Set(so.FindProperty("_description"),"+15% дальности, +5% урона, −15% скорости.");
Set(so.FindProperty("_marchSpeed"),1.7f);
Set(so.FindProperty("_breakRange"),1.5f);
Set(so.FindProperty("_rankSpacing"),0.9f);
Set(so.FindProperty("_fileSpacing"),0.9f);var m=so.FindProperty("_modifiers");m.arraySize=3;
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),4);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),2);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.15f);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_statId"),3);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_modType"),2);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_value"),0.05f);
Set(m.GetArrayElementAtIndex(2).FindPropertyRelative("_statId"),2);
Set(m.GetArrayElementAtIndex(2).FindPropertyRelative("_modType"),2);
Set(m.GetArrayElementAtIndex(2).FindPropertyRelative("_value"),-0.15f);});
Edit("Assets/Configs/Formations/Manipula.asset",so=>{Set(so.FindProperty("_displayName"),"Манипула");
Set(so.FindProperty("_description"),"−8% перезарядки, +8% скорости, −0,5 брони.");
Set(so.FindProperty("_marchSpeed"),2.1f);
Set(so.FindProperty("_breakRange"),1.5f);
Set(so.FindProperty("_rankSpacing"),0.9f);
Set(so.FindProperty("_fileSpacing"),0.9f);var m=so.FindProperty("_modifiers");m.arraySize=3;
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),5);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),2);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),-0.08f);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_statId"),2);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_modType"),2);
Set(m.GetArrayElementAtIndex(1).FindPropertyRelative("_value"),0.08f);
Set(m.GetArrayElementAtIndex(2).FindPropertyRelative("_statId"),8);
Set(m.GetArrayElementAtIndex(2).FindPropertyRelative("_modType"),1);
Set(m.GetArrayElementAtIndex(2).FindPropertyRelative("_value"),-0.5f);});
Edit("Assets/Configs/Upgrades/SharpGladius.asset",so=>{Set(so.FindProperty("_displayName"),"Заточка оружия");
Set(so.FindProperty("_description"),"+8% урона всему отряду до конца забега.");
Set(so.FindProperty("_targetClass"),0);
Set(so.FindProperty("_weight"),4);var m=so.FindProperty("_modifiers");m.arraySize=1;
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),3);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),2);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.08f);});
Edit("Assets/Configs/Upgrades/Soup.asset",so=>{Set(so.FindProperty("_displayName"),"Сытная похлёбка");
Set(so.FindProperty("_description"),"+10% здоровья всему отряду до конца забега.");
Set(so.FindProperty("_targetClass"),0);
Set(so.FindProperty("_weight"),4);var m=so.FindProperty("_modifiers");m.arraySize=1;
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_statId"),1);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_modType"),2);
Set(m.GetArrayElementAtIndex(0).FindPropertyRelative("_value"),0.1f);});
Edit("Assets/Configs/Upgrades/SlaveMarket.asset",so=>{Set(so.FindProperty("_displayName"),"Пополнение");
Set(so.FindProperty("_description"),"+1 мурмиллон в отряд до конца забега.");
Set(so.FindProperty("_targetClass"),0);
Set(so.FindProperty("_weight"),2);var m=so.FindProperty("_modifiers");m.arraySize=0;
});
Edit("Assets/Configs/Wave/Initial.asset",so=>{Set(so.FindProperty("_displayName"),"Первые соперники");
Set(so.FindProperty("_description"),"Учебная схватка. Доступна только в раундах 1–3.");
Set(so.FindProperty("_goldReward"),20);
Set(so.FindProperty("_minimumRound"),1);
Set(so.FindProperty("_maximumRound"),3);
Set(so.FindProperty("_weight"),2);var e=so.FindProperty("_enemies");e.arraySize=1;Set(e.GetArrayElementAtIndex(0).FindPropertyRelative("_config"),Asset("Assets/Configs/Gladiators/Wolf.asset"));Set(e.GetArrayElementAtIndex(0).FindPropertyRelative("_count"),3);});
Edit("Assets/Configs/Wave/Wolfs1.asset",so=>{Set(so.FindProperty("_displayName"),"Волчья стая");
Set(so.FindProperty("_description"),"Много быстрых противников без брони.");
Set(so.FindProperty("_goldReward"),28);
Set(so.FindProperty("_minimumRound"),1);
Set(so.FindProperty("_maximumRound"),0);
Set(so.FindProperty("_weight"),3);var e=so.FindProperty("_enemies");e.arraySize=1;Set(e.GetArrayElementAtIndex(0).FindPropertyRelative("_config"),Asset("Assets/Configs/Gladiators/Wolf.asset"));Set(e.GetArrayElementAtIndex(0).FindPropertyRelative("_count"),4);});
Edit("Assets/Configs/Wave/Murmillo.asset",so=>{Set(so.FindProperty("_displayName"),"Щиты арены");
Set(so.FindProperty("_description"),"Небольшой отряд сбалансированных бойцов.");
Set(so.FindProperty("_id"),"contract.murmillo");
Set(so.FindProperty("_goldReward"),30);
Set(so.FindProperty("_minimumRound"),4);
Set(so.FindProperty("_maximumRound"),0);
Set(so.FindProperty("_weight"),3);var e=so.FindProperty("_enemies");e.arraySize=1;Set(e.GetArrayElementAtIndex(0).FindPropertyRelative("_config"),Asset("Assets/Configs/Gladiators/Murmillo.asset"));Set(e.GetArrayElementAtIndex(0).FindPropertyRelative("_count"),2);});
Edit("Assets/Configs/Wave/Secutors1.asset",so=>{Set(so.FindProperty("_displayName"),"Преследователи");
Set(so.FindProperty("_description"),"Бронированные секуторы с оглушением.");
Set(so.FindProperty("_goldReward"),34);
Set(so.FindProperty("_minimumRound"),8);
Set(so.FindProperty("_maximumRound"),0);
Set(so.FindProperty("_weight"),2);var e=so.FindProperty("_enemies");e.arraySize=1;Set(e.GetArrayElementAtIndex(0).FindPropertyRelative("_config"),Asset("Assets/Configs/Gladiators/Secutor.asset"));Set(e.GetArrayElementAtIndex(0).FindPropertyRelative("_count"),2);});
Edit("Assets/Configs/Wave/Lions1.asset",so=>{Set(so.FindProperty("_displayName"),"Львы арены");
Set(so.FindProperty("_description"),"Выносливые звери с сильным ударом.");
Set(so.FindProperty("_goldReward"),38);
Set(so.FindProperty("_minimumRound"),12);
Set(so.FindProperty("_maximumRound"),0);
Set(so.FindProperty("_weight"),2);var e=so.FindProperty("_enemies");e.arraySize=1;Set(e.GetArrayElementAtIndex(0).FindPropertyRelative("_config"),Asset("Assets/Configs/Gladiators/Lion.asset"));Set(e.GetArrayElementAtIndex(0).FindPropertyRelative("_count"),2);});
Edit("Assets/Configs/Equipment/ItemCatalog.asset",so=>{var a=so.FindProperty("_items");a.arraySize=5;Set(a.GetArrayElementAtIndex(0),Asset("Assets/Configs/Equipment/Gladius.asset"));
Set(a.GetArrayElementAtIndex(1),Asset("Assets/Configs/Equipment/Scutum.asset"));
Set(a.GetArrayElementAtIndex(2),Asset("Assets/Configs/Equipment/LorikaHlamata.asset"));
Set(a.GetArrayElementAtIndex(3),Asset("Assets/Configs/Equipment/Posca.asset"));
Set(a.GetArrayElementAtIndex(4),Asset("Assets/Configs/Equipment/Pilum.asset"));});
Edit("Assets/Configs/Wave/ContractCatalog.asset",so=>{var a=so.FindProperty("_contracts");a.arraySize=5;Set(a.GetArrayElementAtIndex(0),Asset("Assets/Configs/Wave/Initial.asset"));
Set(a.GetArrayElementAtIndex(1),Asset("Assets/Configs/Wave/Wolfs1.asset"));
Set(a.GetArrayElementAtIndex(2),Asset("Assets/Configs/Wave/Murmillo.asset"));
Set(a.GetArrayElementAtIndex(3),Asset("Assets/Configs/Wave/Secutors1.asset"));
Set(a.GetArrayElementAtIndex(4),Asset("Assets/Configs/Wave/Lions1.asset"));});
Edit("Assets/Configs/Wave/ContractCatalog.asset",so=>{Set(so.FindProperty("_enemyGrowthPerRound"),0.12f);
Set(so.FindProperty("_goldGrowthPerRound"),0.06f);
Set(so.FindProperty("_compoundEnemyGrowth"),true);
Set(so.FindProperty("_maximumEnemiesPerSquad"),256);});
Edit("Assets/Configs/Run/RunConfig.asset",so=>{Set(so.FindProperty("_startingGold"),0);
Set(so.FindProperty("_defaultFormation"),null);
Set(so.FindProperty("_contractChoiceCount"),2);
Set(so.FindProperty("_rewardChoiceCount"),2);Set(so.FindProperty("_startingSquad").GetArrayElementAtIndex(0).FindPropertyRelative("_count"),3);});
Edit("Assets/Configs/Run/RosterCatalog.asset",so=>{var a=so.FindProperty("_entries");a.arraySize=5;var e0=a.GetArrayElementAtIndex(0);Set(e0.FindPropertyRelative("_unit"),Asset("Assets/Configs/Gladiators/Murmillo.asset"));Set(e0.FindPropertyRelative("_price"),0);Set(e0.FindPropertyRelative("_requiredBestRound"),0);Set(e0.FindPropertyRelative("_unlockedFromStart"),true);Set(e0.FindPropertyRelative("_startingCount"),3);
var e1=a.GetArrayElementAtIndex(1);Set(e1.FindPropertyRelative("_unit"),Asset("Assets/Configs/Gladiators/Retiatius.asset"));Set(e1.FindPropertyRelative("_price"),350);Set(e1.FindPropertyRelative("_requiredBestRound"),5);Set(e1.FindPropertyRelative("_unlockedFromStart"),false);Set(e1.FindPropertyRelative("_startingCount"),3);
var e2=a.GetArrayElementAtIndex(2);Set(e2.FindPropertyRelative("_unit"),Asset("Assets/Configs/Gladiators/Secutor.asset"));Set(e2.FindPropertyRelative("_price"),550);Set(e2.FindPropertyRelative("_requiredBestRound"),9);Set(e2.FindPropertyRelative("_unlockedFromStart"),false);Set(e2.FindPropertyRelative("_startingCount"),3);
var e3=a.GetArrayElementAtIndex(3);Set(e3.FindPropertyRelative("_unit"),Asset("Assets/Configs/Gladiators/Thraex.asset"));Set(e3.FindPropertyRelative("_price"),750);Set(e3.FindPropertyRelative("_requiredBestRound"),13);Set(e3.FindPropertyRelative("_unlockedFromStart"),false);Set(e3.FindPropertyRelative("_startingCount"),3);
var e4=a.GetArrayElementAtIndex(4);Set(e4.FindPropertyRelative("_unit"),Asset("Assets/Configs/Gladiators/Hoplomach.asset"));Set(e4.FindPropertyRelative("_price"),1000);Set(e4.FindPropertyRelative("_requiredBestRound"),17);Set(e4.FindPropertyRelative("_unlockedFromStart"),false);Set(e4.FindPropertyRelative("_startingCount"),3);});
Edit("Assets/Configs/Formations/FormationCatalog.asset",so=>{var a=so.FindProperty("_entries");a.arraySize=6;var e0=a.GetArrayElementAtIndex(0);Set(e0.FindPropertyRelative("_formation"),Asset("Assets/Configs/Formations/Column.asset"));Set(e0.FindPropertyRelative("_price"),180);Set(e0.FindPropertyRelative("_requiredBestRound"),4);Set(e0.FindPropertyRelative("_unlockedFromStart"),false);
var e1=a.GetArrayElementAtIndex(1);Set(e1.FindPropertyRelative("_formation"),Asset("Assets/Configs/Formations/Circle.asset"));Set(e1.FindPropertyRelative("_price"),240);Set(e1.FindPropertyRelative("_requiredBestRound"),6);Set(e1.FindPropertyRelative("_unlockedFromStart"),false);
var e2=a.GetArrayElementAtIndex(2);Set(e2.FindPropertyRelative("_formation"),Asset("Assets/Configs/Formations/Testudo.asset"));Set(e2.FindPropertyRelative("_price"),400);Set(e2.FindPropertyRelative("_requiredBestRound"),10);Set(e2.FindPropertyRelative("_unlockedFromStart"),false);
var e3=a.GetArrayElementAtIndex(3);Set(e3.FindPropertyRelative("_formation"),Asset("Assets/Configs/Formations/Swine.asset"));Set(e3.FindPropertyRelative("_price"),320);Set(e3.FindPropertyRelative("_requiredBestRound"),8);Set(e3.FindPropertyRelative("_unlockedFromStart"),false);
var e4=a.GetArrayElementAtIndex(4);Set(e4.FindPropertyRelative("_formation"),Asset("Assets/Configs/Formations/Falang.asset"));Set(e4.FindPropertyRelative("_price"),500);Set(e4.FindPropertyRelative("_requiredBestRound"),12);Set(e4.FindPropertyRelative("_unlockedFromStart"),false);
var e5=a.GetArrayElementAtIndex(5);Set(e5.FindPropertyRelative("_formation"),Asset("Assets/Configs/Formations/Manipula.asset"));Set(e5.FindPropertyRelative("_price"),650);Set(e5.FindPropertyRelative("_requiredBestRound"),16);Set(e5.FindPropertyRelative("_unlockedFromStart"),false);});
Edit("Assets/Configs/Blessings/ointment.asset",so=>{Set(so.FindProperty("_price"),35);
Set(so.FindProperty("_power"),150);
Set(so.FindProperty("_radius"),1.6f);
Set(so.FindProperty("_duration"),0);
Set(so.FindProperty("_speedFactor"),1);
Set(so.FindProperty("_description"),"Восстанавливает 150 здоровья живым бойцам в радиусе 1,6, включая врагов. Один заряд.");});
Edit("Assets/Configs/Blessings/tar.asset",so=>{Set(so.FindProperty("_price"),50);
Set(so.FindProperty("_power"),100);
Set(so.FindProperty("_radius"),1.6f);
Set(so.FindProperty("_duration"),4);
Set(so.FindProperty("_speedFactor"),0.65f);
Set(so.FindProperty("_description"),"100 урона с учётом брони всем в радиусе 1,6; скорость −35% на 4 секунды. Задевает своих. Один заряд.");});
Edit("Assets/Configs/Blessings/fervor.asset",so=>{Set(so.FindProperty("_price"),20);
Set(so.FindProperty("_power"),0);
Set(so.FindProperty("_radius"),1.8f);
Set(so.FindProperty("_duration"),5);
Set(so.FindProperty("_speedFactor"),1.35f);
Set(so.FindProperty("_description"),"Скорость передвижения +35% на 5 секунд в радиусе 1,8, включая врагов. Не ускоряет атаки. Один заряд.");});
Edit("Assets/Configs/Abilities/Net.asset",so=>{Set(so.FindProperty("_displayName"),"Сеть");
Set(so.FindProperty("_description"),"Замедляет цель на 35% на 2 секунды.");
Set(so.FindProperty("_cooldown"),8);
Set(so.FindProperty("_range"),1.8f);
Set(so.FindProperty("_duration"),2);
Set(so.FindProperty("_magnitude"),0.65f);});
Edit("Assets/Configs/Abilities/ShieldDash.asset",so=>{Set(so.FindProperty("_displayName"),"Удар щитом");
Set(so.FindProperty("_description"),"Оглушает цель на 0,45 секунды.");
Set(so.FindProperty("_cooldown"),10);
Set(so.FindProperty("_range"),1.3f);
Set(so.FindProperty("_duration"),0.45f);
Set(so.FindProperty("_magnitude"),0);});
Edit("Assets/Configs/Abilities/Haste.asset",so=>{Set(so.FindProperty("_displayName"),"Рывок");
Set(so.FindProperty("_description"),"Ускоряет передвижение на 35% на 2 секунды.");
Set(so.FindProperty("_cooldown"),9);
Set(so.FindProperty("_range"),0);
Set(so.FindProperty("_duration"),2);
Set(so.FindProperty("_magnitude"),1.35f);});
AssetDatabase.SaveAssets();return "Balance v1 applied";
